//
//  movable_id.h
//  wad_kit
//
//  Created by Евгений Лютц on 06.06.20.
//  Copyright © 2020 Eugene Lutz. All rights reserved.
//

#ifndef wad_kit_movable_id_h
#define wad_kit_movable_id_h

typedef enum MOVABLE_ID
{
	MOVABLE_ID_LARA,
	
	MOVABLE_ID_PISTOLS_ANIM,
	MOVABLE_ID_UZI_ANIM,
	MOVABLE_ID_SHOTGUN_ANIM,
	MOVABLE_ID_CROSSBOW_ANIM,
	MOVABLE_ID_GRENADE_GUN_ANIM,
	MOVABLE_ID_SIXSHOOTER_ANIM,
	MOVABLE_ID_FLARE_ANIM,
	
	MOVABLE_ID_LARA_SKIN,
	MOVABLE_ID_LARA_SKIN_JOINTS,
	
	MOVABLE_ID_LARA_SCREAM,
	
	MOVABLE_ID_LARA_CROSSBOW_LASER,
	MOVABLE_ID_LARA_REVOLVER_LASER,
	
	MOVABLE_ID_LARA_HOLSTERS,
	MOVABLE_ID_LARA_HOLSTERS_PISTOLS,
	MOVABLE_ID_LARA_HOLSTERS_UZIS,
	MOVABLE_ID_LARA_HOLSTERS_SIXSHOOTER,
	
	MOVABLE_ID_LARA_SPEECH_HEAD1,
	MOVABLE_ID_LARA_SPEECH_HEAD2,
	MOVABLE_ID_LARA_SPEECH_HEAD3,
	MOVABLE_ID_LARA_SPEECH_HEAD4,
	
	MOVABLE_ID_ACTOR1_SPEECH_HEAD1,
	MOVABLE_ID_ACTOR1_SPEECH_HEAD2,
	
	MOVABLE_ID_ACTOR2_SPEECH_HEAD1,
	MOVABLE_ID_ACTOR2_SPEECH_HEAD2,
	
	MOVABLE_ID_LARA_WATER_MESH,
	MOVABLE_ID_LARA_PETROL_MESH,
	MOVABLE_ID_LARA_DIRT_MESH,
	
	MOVABLE_ID_CROWBAR_ANIM,
	MOVABLE_ID_TORCH_ANIM,
	
	MOVABLE_ID_HAIR,
	
	MOVABLE_ID_MOTORBIKE,
	MOVABLE_ID_JEEP,
	MOVABLE_ID_VEHICLE_EXTRA,

	MOVABLE_ID_ENEMY_JEEP,

	MOVABLE_ID_SKELETON,	MOVABLE_ID_SKELETON_MIP,
	MOVABLE_ID_GUIDE,		MOVABLE_ID_GUIDE_MIP,
	MOVABLE_ID_VON_CROY,	MOVABLE_ID_VON_CROY_MIP,
	MOVABLE_ID_BADDY_1,		MOVABLE_ID_BADDY_1_MIP,
	MOVABLE_ID_BADDY_2,		MOVABLE_ID_BADDY_2_MIP,
	MOVABLE_ID_SETHA,		MOVABLE_ID_SETHA_MIP,

	MOVABLE_ID_MUMMY,		MOVABLE_ID_MUMMY_MIP,
	MOVABLE_ID_SPHINX,		MOVABLE_ID_SPHINX_MIP,
	MOVABLE_ID_CROCODILE,	MOVABLE_ID_CROCODILE_MIP,
	MOVABLE_ID_HORSEMAN,	MOVABLE_ID_HORSEMAN_MIP,
	MOVABLE_ID_SCORPION,	MOVABLE_ID_SCORPION_MIP,
	MOVABLE_ID_JEAN_YVES,	MOVABLE_ID_JEAN_YVES_MIP,
	MOVABLE_ID_TROOPS,		MOVABLE_ID_TROOPS_MIP,
	MOVABLE_ID_KNIGHTS_TEMPLAR,	MOVABLE_ID_KNIGHTS_TEMPLAR_MIP,
	MOVABLE_ID_MUTANT,			MOVABLE_ID_MUTANT_MIP,
	MOVABLE_ID_HORSE,			MOVABLE_ID_HORSE_MIP,
	MOVABLE_ID_BABOON_NORMAL,	MOVABLE_ID_BABOON_NORMAL_MIP,
	MOVABLE_ID_BABOON_INV,		MOVABLE_ID_BABOON_INV_MIP,
	MOVABLE_ID_BABOON_SILENT,	MOVABLE_ID_BABOON_SILENT_MIP,
	MOVABLE_ID_WILD_BOAR,		MOVABLE_ID_WILD_BOAR_MIP,
	MOVABLE_ID_HARPY,			MOVABLE_ID_HARPY_MIP,
	MOVABLE_ID_DEMIGOD1,		MOVABLE_ID_DEMIGOD1_MIP,
	MOVABLE_ID_DEMIGOD2,		MOVABLE_ID_DEMIGOD2_MIP,
	MOVABLE_ID_DEMIGOD3,		MOVABLE_ID_DEMIGOD3_MIP,
	MOVABLE_ID_LITTLE_BEETLE,
	MOVABLE_ID_BIG_BEETLE,		MOVABLE_ID_BIG_BEETLE_MIP,
	
	MOVABLE_ID_WRAITH1,
	MOVABLE_ID_WRAITH2,
	MOVABLE_ID_WRAITH3,
	MOVABLE_ID_WRAITH4,
	
	MOVABLE_ID_BAT,
	MOVABLE_ID_DOG,				MOVABLE_ID_DOG_MIP,
	MOVABLE_ID_HAMMERHEAD,		MOVABLE_ID_HAMMERHEAD_MIP,
	MOVABLE_ID_SAS,				MOVABLE_ID_SAS_MIP,
	MOVABLE_ID_SAS_DYING,		MOVABLE_ID_SAS_DYING_MIP,
	MOVABLE_ID_SAS_CAPTAIN,		MOVABLE_ID_SAS_CAPTAIN_MIP,
	MOVABLE_ID_SAS_DRAG_BLOKE,
	MOVABLE_ID_AHMET,			MOVABLE_ID_AHMET_MIP,
	MOVABLE_ID_LARA_DOUBLE,		MOVABLE_ID_LARA_DOUBLE_MIP,
	MOVABLE_ID_SMALL_SCORPION,
	MOVABLE_ID_FISH,

	MOVABLE_ID_GAME_PIECE1,
	MOVABLE_ID_GAME_PIECE2,
	MOVABLE_ID_GAME_PIECE3,
	
	MOVABLE_ID_ENEMY_PIECE,
	MOVABLE_ID_WHEEL_OF_FORTUNE,
	MOVABLE_ID_SCALES,

	MOVABLE_ID_DARTS,
	MOVABLE_ID_DART_EMITTER,
	MOVABLE_ID_HOMING_DART_EMITTER,
	
	MOVABLE_ID_FALLING_CEILING,
	MOVABLE_ID_FALLING_BLOCK,
	MOVABLE_ID_FALLING_BLOCK2,
	
	MOVABLE_ID_SMASHABLE_BIKE_WALL,
	MOVABLE_ID_SMASHABLE_BIKE_FLOOR,
	
	MOVABLE_ID_TRAPDOOR1,
	MOVABLE_ID_TRAPDOOR2,
	MOVABLE_ID_TRAPDOOR3,
	
	MOVABLE_ID_FLOOR_TRAPDOOR1,
	MOVABLE_ID_FLOOR_TRAPDOOR2,
	
	MOVABLE_ID_CEILING_TRAPDOOR1,
	MOVABLE_ID_CEILING_TRAPDOOR2,
	
	MOVABLE_ID_SCALING_TRAPDOOR,
	
	MOVABLE_ID_ROLLINGBALL,
	
	MOVABLE_ID_SPIKEY_FLOOR,
	MOVABLE_ID_TEETH_SPIKES,
	MOVABLE_ID_JOBY_SPIKES,
	MOVABLE_ID_SLICER_DICER,
	
	MOVABLE_ID_CHAIN,
	MOVABLE_ID_PLOUGH,
	MOVABLE_ID_STARGATE,
	MOVABLE_ID_HAMMER,
	MOVABLE_ID_BURNING_FLOOR,
	MOVABLE_ID_COG,
	MOVABLE_ID_SPIKEBALL,
	
	MOVABLE_ID_FLAME,
	MOVABLE_ID_FLAME_EMITTER,
	MOVABLE_ID_FLAME_EMITTER2,
	MOVABLE_ID_FLAME_EMITTER3,
	
	MOVABLE_ID_ROPE,
	MOVABLE_ID_FIREROPE,
	
	MOVABLE_ID_POLEROPE,
	
	MOVABLE_ID_ONEBLOCK_PLATFORM,
	MOVABLE_ID_TWOBLOCK_PLATFORM,
	
	MOVABLE_ID_RAISING_BLOCK1,
	MOVABLE_ID_RAISING_BLOCK2,
	
	MOVABLE_ID_EXPANDING_PLATFORM,
	
	MOVABLE_ID_SQUISHY_BLOCK1,
	MOVABLE_ID_SQUISHY_BLOCK2,
	
	MOVABLE_ID_PUSHABLE_OBJECT1,
	MOVABLE_ID_PUSHABLE_OBJECT2,
	MOVABLE_ID_PUSHABLE_OBJECT3,
	MOVABLE_ID_PUSHABLE_OBJECT4,
	MOVABLE_ID_PUSHABLE_OBJECT5,
	
	MOVABLE_ID_TRIPWIRE,
	MOVABLE_ID_SENTRY_GUN,
	MOVABLE_ID_MINE,
	MOVABLE_ID_MAPPER,
	MOVABLE_ID_OBELISK,
	
	MOVABLE_ID_FLOOR_4BLADE,
	MOVABLE_ID_ROOF_4BLADE,
	MOVABLE_ID_BIRD_BLADE,
	MOVABLE_ID_CATWALK_BLADE,
	MOVABLE_ID_MOVING_BLADE,
	MOVABLE_ID_PLINTH_BLADE,
	MOVABLE_ID_SETH_BLADE,
	
	MOVABLE_ID_LIGHTNING_CONDUCTOR,
	MOVABLE_ID_ELEMENT_PUZZLE,

	MOVABLE_ID_PUZZLE_ITEM1,
	MOVABLE_ID_PUZZLE_ITEM2,
	MOVABLE_ID_PUZZLE_ITEM3,
	MOVABLE_ID_PUZZLE_ITEM4,
	MOVABLE_ID_PUZZLE_ITEM5,
	MOVABLE_ID_PUZZLE_ITEM6,
	MOVABLE_ID_PUZZLE_ITEM7,
	MOVABLE_ID_PUZZLE_ITEM8,
	MOVABLE_ID_PUZZLE_ITEM9,
	MOVABLE_ID_PUZZLE_ITEM10,
	MOVABLE_ID_PUZZLE_ITEM11,
	MOVABLE_ID_PUZZLE_ITEM12,

	MOVABLE_ID_PUZZLE_ITEM1_COMBO1,
	MOVABLE_ID_PUZZLE_ITEM1_COMBO2,
	
	MOVABLE_ID_PUZZLE_ITEM2_COMBO1,
	MOVABLE_ID_PUZZLE_ITEM2_COMBO2,
	
	MOVABLE_ID_PUZZLE_ITEM3_COMBO1,
	MOVABLE_ID_PUZZLE_ITEM3_COMBO2,
	
	MOVABLE_ID_PUZZLE_ITEM4_COMBO1,
	MOVABLE_ID_PUZZLE_ITEM4_COMBO2,
	
	MOVABLE_ID_PUZZLE_ITEM5_COMBO1,
	MOVABLE_ID_PUZZLE_ITEM5_COMBO2,
	
	MOVABLE_ID_PUZZLE_ITEM6_COMBO1,
	MOVABLE_ID_PUZZLE_ITEM6_COMBO2,
	
	MOVABLE_ID_PUZZLE_ITEM7_COMBO1,
	MOVABLE_ID_PUZZLE_ITEM7_COMBO2,
	
	MOVABLE_ID_PUZZLE_ITEM8_COMBO1,
	MOVABLE_ID_PUZZLE_ITEM8_COMBO2,

	
	MOVABLE_ID_KEY_ITEM1,
	MOVABLE_ID_KEY_ITEM2,
	MOVABLE_ID_KEY_ITEM3,
	MOVABLE_ID_KEY_ITEM4,
	MOVABLE_ID_KEY_ITEM5,
	MOVABLE_ID_KEY_ITEM6,
	MOVABLE_ID_KEY_ITEM7,
	MOVABLE_ID_KEY_ITEM8,
	MOVABLE_ID_KEY_ITEM9,
	MOVABLE_ID_KEY_ITEM10,
	MOVABLE_ID_KEY_ITEM11,
	MOVABLE_ID_KEY_ITEM12,

	MOVABLE_ID_KEY_ITEM1_COMBO1,
	MOVABLE_ID_KEY_ITEM1_COMBO2,
	
	MOVABLE_ID_KEY_ITEM2_COMBO1,
	MOVABLE_ID_KEY_ITEM2_COMBO2,
	
	MOVABLE_ID_KEY_ITEM3_COMBO1,
	MOVABLE_ID_KEY_ITEM3_COMBO2,
	
	MOVABLE_ID_KEY_ITEM4_COMBO1,
	MOVABLE_ID_KEY_ITEM4_COMBO2,
	
	MOVABLE_ID_KEY_ITEM5_COMBO1,
	MOVABLE_ID_KEY_ITEM5_COMBO2,
	
	MOVABLE_ID_KEY_ITEM6_COMBO1,
	MOVABLE_ID_KEY_ITEM6_COMBO2,
	
	MOVABLE_ID_KEY_ITEM7_COMBO1,
	MOVABLE_ID_KEY_ITEM7_COMBO2,
	
	MOVABLE_ID_KEY_ITEM8_COMBO1,
	MOVABLE_ID_KEY_ITEM8_COMBO2,
	

	MOVABLE_ID_PICKUP_ITEM1,
	MOVABLE_ID_PICKUP_ITEM2,
	MOVABLE_ID_PICKUP_ITEM3,
	MOVABLE_ID_PICKUP_ITEM4,

	MOVABLE_ID_PICKUP_ITEM1_COMBO1,
	MOVABLE_ID_PICKUP_ITEM1_COMBO2,
	
	MOVABLE_ID_PICKUP_ITEM2_COMBO1,
	MOVABLE_ID_PICKUP_ITEM2_COMBO2,
	
	MOVABLE_ID_PICKUP_ITEM3_COMBO1,
	MOVABLE_ID_PICKUP_ITEM3_COMBO2,
	
	MOVABLE_ID_PICKUP_ITEM4_COMBO1,
	MOVABLE_ID_PICKUP_ITEM4_COMBO2,
	

	MOVABLE_ID_EXAMINE1,
	MOVABLE_ID_EXAMINE2,
	MOVABLE_ID_EXAMINE3,

	MOVABLE_ID_CROWBAR_ITEM,
	MOVABLE_ID_BURNING_TORCH_ITEM,
	
	MOVABLE_ID_CLOCKWORK_BEETLE,
	MOVABLE_ID_CLOCKWORK_BEETLE_COMBO1,
	MOVABLE_ID_CLOCKWORK_BEETLE_COMBO2,
	
	MOVABLE_ID_MINE_DETECTOR,

	MOVABLE_ID_QUEST_ITEM1,
	MOVABLE_ID_QUEST_ITEM2,
	MOVABLE_ID_QUEST_ITEM3,
	MOVABLE_ID_QUEST_ITEM4,
	MOVABLE_ID_QUEST_ITEM5,
	MOVABLE_ID_QUEST_ITEM6,
	
	MOVABLE_ID_MAP,
	MOVABLE_ID_SECRET_MAP,
	
	MOVABLE_ID_PUZZLE_HOLE1,
	MOVABLE_ID_PUZZLE_HOLE2,
	MOVABLE_ID_PUZZLE_HOLE3,
	MOVABLE_ID_PUZZLE_HOLE4,
	MOVABLE_ID_PUZZLE_HOLE5,
	MOVABLE_ID_PUZZLE_HOLE6,
	MOVABLE_ID_PUZZLE_HOLE7,
	MOVABLE_ID_PUZZLE_HOLE8,
	MOVABLE_ID_PUZZLE_HOLE9,
	MOVABLE_ID_PUZZLE_HOLE10,
	MOVABLE_ID_PUZZLE_HOLE11,
	MOVABLE_ID_PUZZLE_HOLE12,
	
	MOVABLE_ID_PUZZLE_DONE1,
	MOVABLE_ID_PUZZLE_DONE2,
	MOVABLE_ID_PUZZLE_DONE3,
	MOVABLE_ID_PUZZLE_DONE4,
	MOVABLE_ID_PUZZLE_DONE5,
	MOVABLE_ID_PUZZLE_DONE6,
	MOVABLE_ID_PUZZLE_DONE7,
	MOVABLE_ID_PUZZLE_DONE8,
	MOVABLE_ID_PUZZLE_DONE9,
	MOVABLE_ID_PUZZLE_DONE10,
	MOVABLE_ID_PUZZLE_DONE11,
	MOVABLE_ID_PUZZLE_DONE12,
	
	MOVABLE_ID_KEY_HOLE1,
	MOVABLE_ID_KEY_HOLE2,
	MOVABLE_ID_KEY_HOLE3,
	MOVABLE_ID_KEY_HOLE4,
	MOVABLE_ID_KEY_HOLE5,
	MOVABLE_ID_KEY_HOLE6,
	MOVABLE_ID_KEY_HOLE7,
	MOVABLE_ID_KEY_HOLE8,
	MOVABLE_ID_KEY_HOLE9,
	MOVABLE_ID_KEY_HOLE10,
	MOVABLE_ID_KEY_HOLE11,
	MOVABLE_ID_KEY_HOLE12,

	MOVABLE_ID_WATERSKIN1_EMPTY,
	MOVABLE_ID_WATERSKIN1_1,
	MOVABLE_ID_WATERSKIN1_2,
	MOVABLE_ID_WATERSKIN1_3,
	
	MOVABLE_ID_WATERSKIN2_EMPTY,
	MOVABLE_ID_WATERSKIN2_1,
	MOVABLE_ID_WATERSKIN2_2,
	MOVABLE_ID_WATERSKIN2_3,
	MOVABLE_ID_WATERSKIN2_4,
	MOVABLE_ID_WATERSKIN2_5,

	MOVABLE_ID_SWITCH_TYPE1,
	MOVABLE_ID_SWITCH_TYPE2,
	MOVABLE_ID_SWITCH_TYPE3,
	MOVABLE_ID_SWITCH_TYPE4,
	MOVABLE_ID_SWITCH_TYPE5,
	MOVABLE_ID_SWITCH_TYPE6,
	MOVABLE_ID_SWITCH_TYPE7,
	MOVABLE_ID_SWITCH_TYPE8,
	
	MOVABLE_ID_UNDERWATER_SWITCH1,
	MOVABLE_ID_UNDERWATER_SWITCH2,
	
	MOVABLE_ID_TURN_SWITCH,
	MOVABLE_ID_COG_SWITCH,
	MOVABLE_ID_LEVER_SWITCH,
	MOVABLE_ID_JUMP_SWITCH,
	MOVABLE_ID_CROWBAR_SWITCH,
	
	MOVABLE_ID_PULLEY,
	
	MOVABLE_ID_DOOR_TYPE1,
	MOVABLE_ID_DOOR_TYPE2,
	MOVABLE_ID_DOOR_TYPE3,
	MOVABLE_ID_DOOR_TYPE4,
	MOVABLE_ID_DOOR_TYPE5,
	MOVABLE_ID_DOOR_TYPE6,
	MOVABLE_ID_DOOR_TYPE7,
	MOVABLE_ID_DOOR_TYPE8,
	
	MOVABLE_ID_PUSHPULL_DOOR1,
	MOVABLE_ID_PUSHPULL_DOOR2,
	
	MOVABLE_ID_KICK_DOOR1,
	MOVABLE_ID_KICK_DOOR2,
	
	MOVABLE_ID_UNDERWATER_DOOR,
	
	MOVABLE_ID_DOUBLE_DOORS,
	
	MOVABLE_ID_BRIDGE_FLAT,
	
	MOVABLE_ID_BRIDGE_TILT1,
	MOVABLE_ID_BRIDGE_TILT2,

	MOVABLE_ID_SARCOPHAGUS,

	MOVABLE_ID_SEQUENCE_DOOR1,
	MOVABLE_ID_SEQUENCE_SWITCH1,
	MOVABLE_ID_SEQUENCE_SWITCH2,
	MOVABLE_ID_SEQUENCE_SWITCH3,

	MOVABLE_ID_SARCOPHAGUS_CUT,
	MOVABLE_ID_HORUS_STATUE,
	MOVABLE_ID_GOD_HEAD,
	MOVABLE_ID_SETH_DOOR,
	MOVABLE_ID_STATUE_PLINTH,

	MOVABLE_ID_PISTOLS_ITEM,
	MOVABLE_ID_PISTOLS_AMMO_ITEM,
	MOVABLE_ID_UZI_ITEM,
	MOVABLE_ID_UZI_AMMO_ITEM,
	MOVABLE_ID_SHOTGUN_ITEM,
	MOVABLE_ID_SHOTGUN_AMMO1_ITEM,
	MOVABLE_ID_SHOTGUN_AMMO2_ITEM,
	MOVABLE_ID_CROSSBOW_ITEM,
	MOVABLE_ID_CROSSBOW_AMMO1_ITEM,
	MOVABLE_ID_CROSSBOW_AMMO2_ITEM,
	MOVABLE_ID_CROSSBOW_AMMO3_ITEM,
	MOVABLE_ID_CROSSBOW_BOLT,
	MOVABLE_ID_GRENADE_GUN_ITEM,
	MOVABLE_ID_GRENADE_GUN_AMMO1_ITEM,
	MOVABLE_ID_GRENADE_GUN_AMMO2_ITEM,
	MOVABLE_ID_GRENADE_GUN_AMMO3_ITEM,
	MOVABLE_ID_GRENADE,
	MOVABLE_ID_SIXSHOOTER_ITEM,
	MOVABLE_ID_SIXSHOOTER_AMMO_ITEM,
	
	MOVABLE_ID_BIGMEDI_ITEM,
	MOVABLE_ID_SMALLMEDI_ITEM,
	
	MOVABLE_ID_LASERSIGHT_ITEM,
	MOVABLE_ID_BINOCULARS_ITEM,
	MOVABLE_ID_FLARE_ITEM,
	MOVABLE_ID_FLARE_INV_ITEM,
	MOVABLE_ID_DIARY_ITEM,
	MOVABLE_ID_COMPASS_ITEM,
	
	MOVABLE_ID_MEMCARD_LOAD_INV_ITEM,
	MOVABLE_ID_MEMCARD_SAVE_INV_ITEM,
	MOVABLE_ID_PC_LOAD_INV_ITEM,
	MOVABLE_ID_PC_SAVE_INV_ITEM,

	MOVABLE_ID_SMOKE_EMITTER_WHITE,
	MOVABLE_ID_SMOKE_EMITTER_BLACK,
	MOVABLE_ID_STEAM_EMITTER,
	
	MOVABLE_ID_EARTHQUAKE,
	MOVABLE_ID_BUBBLES,
	MOVABLE_ID_WATERFALLMIST,
	
	MOVABLE_ID_GUNSHELL,
	MOVABLE_ID_SHOTGUNSHELL,
	
	MOVABLE_ID_GUN_FLASH,
	MOVABLE_ID_BUTTERFLY,
	MOVABLE_ID_SPRINKLER,

	MOVABLE_ID_RED_LIGHT,
	MOVABLE_ID_GREEN_LIGHT,
	MOVABLE_ID_BLUE_LIGHT,
	MOVABLE_ID_AMBER_LIGHT,
	MOVABLE_ID_WHITE_LIGHT,
	MOVABLE_ID_BLINKING_LIGHT,
	MOVABLE_ID_LENS_FLARE,

	MOVABLE_ID_AI_GUARD,
	MOVABLE_ID_AI_AMBUSH,
	MOVABLE_ID_AI_PATROL1,
	MOVABLE_ID_AI_MODIFY,
	MOVABLE_ID_AI_FOLLOW,
	MOVABLE_ID_AI_PATROL2,
	MOVABLE_ID_AI_X1,
	MOVABLE_ID_AI_X2,
	
	MOVABLE_ID_LARA_START_POS,

	MOVABLE_ID_KILL_ALL_TRIGGERS,
	MOVABLE_ID_TRIGGER_TRIGGERER,
	
	MOVABLE_ID_SMASH_OBJECT1,
	MOVABLE_ID_SMASH_OBJECT2,
	MOVABLE_ID_SMASH_OBJECT3,
	MOVABLE_ID_SMASH_OBJECT4,
	MOVABLE_ID_SMASH_OBJECT5,
	MOVABLE_ID_SMASH_OBJECT6,
	MOVABLE_ID_SMASH_OBJECT7,
	MOVABLE_ID_SMASH_OBJECT8,
	
	MOVABLE_ID_MESHSWAP1,
	MOVABLE_ID_MESHSWAP2,
	MOVABLE_ID_MESHSWAP3,
	
	MOVABLE_ID_DEATH_SLIDE,
	
	MOVABLE_ID_BODY_PART,
	
	MOVABLE_ID_CAMERA_TARGET,
	
	MOVABLE_ID_WATERFALL1,
	MOVABLE_ID_WATERFALL2,
	MOVABLE_ID_WATERFALL3,
	
	MOVABLE_ID_PLANET_EFFECT,
	
	MOVABLE_ID_ANIMATING1,	MOVABLE_ID_ANIMATING1_MIP,
	MOVABLE_ID_ANIMATING2,	MOVABLE_ID_ANIMATING2_MIP,
	MOVABLE_ID_ANIMATING3,	MOVABLE_ID_ANIMATING3_MIP,
	MOVABLE_ID_ANIMATING4,	MOVABLE_ID_ANIMATING4_MIP,
	MOVABLE_ID_ANIMATING5,	MOVABLE_ID_ANIMATING5_MIP,
	MOVABLE_ID_ANIMATING6,	MOVABLE_ID_ANIMATING6_MIP,
	MOVABLE_ID_ANIMATING7,	MOVABLE_ID_ANIMATING7_MIP,
	MOVABLE_ID_ANIMATING8,	MOVABLE_ID_ANIMATING8_MIP,
	MOVABLE_ID_ANIMATING9,	MOVABLE_ID_ANIMATING9_MIP,
	MOVABLE_ID_ANIMATING10,	MOVABLE_ID_ANIMATING10_MIP,
	MOVABLE_ID_ANIMATING11,	MOVABLE_ID_ANIMATING11_MIP,
	MOVABLE_ID_ANIMATING12,	MOVABLE_ID_ANIMATING12_MIP,
	MOVABLE_ID_ANIMATING13,	MOVABLE_ID_ANIMATING13_MIP,
	MOVABLE_ID_ANIMATING14,	MOVABLE_ID_ANIMATING14_MIP,
	MOVABLE_ID_ANIMATING15,	MOVABLE_ID_ANIMATING15_MIP,
	MOVABLE_ID_ANIMATING16,	MOVABLE_ID_ANIMATING16_MIP,
	
	MOVABLE_ID_HORIZON,
	MOVABLE_ID_SKY_GRAPHICS,
	MOVABLE_ID_BINOCULAR_GRAPHICS,
	MOVABLE_ID_TARGET_GRAPHICS,

	MOVABLE_ID_DEFAULT_SPRITES,
	MOVABLE_ID_MISC_SPRITES,

	MOVABLE_ID_NUMBER_OBJECTS
}
MOVABLE_ID;

#endif /* wad_kit_movable_id_h */
