//
//  static_object_id.h
//  wad_kit
//
//  Created by Евгений Лютц on 06.06.20.
//  Copyright © 2020 Eugene Lutz. All rights reserved.
//

#ifndef wad_kit_static_object_id_h
#define wad_kit_static_object_id_h

typedef enum STATIC_ID
{
	STATIC_ID_PLANT0, STATIC_ID_PLANT1, STATIC_ID_PLANT2, STATIC_ID_PLANT3, STATIC_ID_PLANT4,
	STATIC_ID_PLANT5, STATIC_ID_PLANT6, STATIC_ID_PLANT7, STATIC_ID_PLANT8, STATIC_ID_PLANT9,
	
	STATIC_ID_FURNITURE0, STATIC_ID_FURNITURE1, STATIC_ID_FURNITURE2, STATIC_ID_FURNITURE3, STATIC_ID_FURNITURE4,
	STATIC_ID_FURNITURE5, STATIC_ID_FURNITURE6, STATIC_ID_FURNITURE7, STATIC_ID_FURNITURE8, STATIC_ID_FURNITURE9,
	
	STATIC_ID_ROCK0, STATIC_ID_ROCK1, STATIC_ID_ROCK2, STATIC_ID_ROCK3, STATIC_ID_ROCK4,
	STATIC_ID_ROCK5, STATIC_ID_ROCK6, STATIC_ID_ROCK7, STATIC_ID_ROCK8, STATIC_ID_ROCK9,
	
	STATIC_ID_ARCHITECTURE0, STATIC_ID_ARCHITECTURE1, STATIC_ID_ARCHITECTURE2, STATIC_ID_ARCHITECTURE3,
	STATIC_ID_ARCHITECTURE4, STATIC_ID_ARCHITECTURE5, STATIC_ID_ARCHITECTURE6, STATIC_ID_ARCHITECTURE7,
	STATIC_ID_ARCHITECTURE8, STATIC_ID_ARCHITECTURE9,
	
	STATIC_ID_DEBRIS0, STATIC_ID_DEBRIS1, STATIC_ID_DEBRIS2, STATIC_ID_DEBRIS3, STATIC_ID_DEBRIS4,
	STATIC_ID_DEBRIS5, STATIC_ID_DEBRIS6, STATIC_ID_DEBRIS7, STATIC_ID_DEBRIS8, STATIC_ID_DEBRIS9,
	
	STATIC_ID_SHATTER0, STATIC_ID_SHATTER1, STATIC_ID_SHATTER2, STATIC_ID_SHATTER3, STATIC_ID_SHATTER4,
	STATIC_ID_SHATTER5, STATIC_ID_SHATTER6, STATIC_ID_SHATTER7, STATIC_ID_SHATTER8, STATIC_ID_SHATTER9,
	
	STATIC_ID_NUMBER_STATIC_OBJECTS
}
STATIC_ID;

#endif /* wad_kit_static_object_id_h */
